# Generated by Django 4.1.1 on 2022-10-08 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('surveyor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('system_type', models.CharField(choices=[('IA', 'Intruder Alarm'), ('FA', 'Fire Alarm'), ('AC', 'Access Control'), ('CC', 'CCTV System'), ('FE', 'Fire Extinguishers'), ('OT', 'Other')], default='IA', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('premises_type', models.CharField(choices=[('DO', 'Domestic System'), ('CO', 'Commercial System'), ('OT', 'Other')], default='CO', max_length=2)),
                ('quote_status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('CO', 'Converted')], default='OP', max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=320)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('quotation_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('quote_sale_value', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='customer.customer')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='surveyor.surveyor')),
            ],
        ),
    ]
